import { describe, expect, it } from "vitest";

import { resolveLocalizedOfferTerm } from "./localized-offer-terms";

const commonOfferTerms = [
  "americano",
  "cappuccino",
  "mocha",
  "macchiato",
  "chai latte",
  "matcha latte",
  "hot chocolate",
  "iced coffee",
  "iced tea",
  "lemonade",
  "smoothie",
  "milkshake",
  "soda",
  "fountain drink",
  "bottled water",
  "juice",
  "orange juice",
  "apple juice",
  "donut",
  "cinnamon roll",
  "brownie",
  "cupcake",
  "cake slice",
  "cheesecake slice",
  "pie slice",
  "danish",
  "biscotti",
  "banana bread",
  "toast",
  "avocado toast",
  "pancakes",
  "waffle",
  "omelet",
  "hash browns",
  "breakfast sandwich",
  "breakfast burrito",
  "breakfast taco",
  "yogurt parfait",
  "granola bowl",
  "sandwich",
  "turkey sandwich",
  "chicken sandwich",
  "grilled cheese sandwich",
  "wrap",
  "chicken wrap",
  "burger",
  "cheeseburger",
  "veggie burger",
  "hot dog",
  "taco",
  "burrito",
  "quesadilla",
  "pizza slice",
  "salad",
  "caesar salad",
  "soup",
  "ramen",
  "rice bowl",
  "poke bowl",
  "sushi roll",
  "fries",
  "onion rings",
  "chicken wings",
  "chicken tenders",
  "chicken nuggets",
  "nachos",
  "chips and salsa",
  "appetizer",
  "side dish",
  "entree",
  "lunch combo",
  "dinner entree",
  "combo meal",
  "kids meal",
  "ice cream",
  "ice cream scoop",
  "frozen yogurt",
  "gelato",
  "pretzel",
  "popcorn",
  "chips",
  "salsa",
  "guacamole",
  "hummus",
  "falafel",
  "gyro",
  "pita",
  "flatbread",
  "garlic bread",
  "pasta",
  "spaghetti",
  "pho",
  "curry bowl",
  "dumplings",
  "spring rolls",
  "boba tea",
  "bubble tea",
  "milk tea",
  "green tea",
  "herbal tea",
] as const;

const spanishSourceOfferTermsToEnglish = [
  ["tacos al pastor", "al pastor tacos"],
  ["tacos de carne asada", "carne asada tacos"],
  ["tacos de barbacoa", "barbacoa tacos"],
  ["tacos de carnitas", "carnitas tacos"],
  ["tacos de pescado", "fish tacos"],
  ["tacos de camar\xf3n", "shrimp tacos"],
  ["burrito de carne asada", "carne asada burrito"],
  ["burrito de frijoles", "bean burrito"],
  ["quesadilla de queso", "cheese quesadilla"],
  ["quesadilla de pollo", "chicken quesadilla"],
  ["enchiladas verdes", "green enchiladas"],
  ["enchiladas rojas", "red enchiladas"],
  ["enchiladas de pollo", "chicken enchiladas"],
  ["chilaquiles verdes", "green chilaquiles"],
  ["chilaquiles rojos", "red chilaquiles"],
  ["huevos rancheros", "ranch-style eggs"],
  ["tamal", "tamale"],
  ["tamales", "tamales"],
  ["tamal de elote", "sweet corn tamale"],
  ["mole poblano", "mole poblano"],
  ["pozole", "pozole"],
  ["menudo", "menudo"],
  ["birria", "birria"],
  ["birria de res", "beef birria"],
  ["consom\xe9 de birria", "birria consomme"],
  ["sopes", "sopes"],
  ["gorditas", "gorditas"],
  ["huaraches", "huaraches"],
  ["tostadas", "tostadas"],
  ["tostada de ceviche", "ceviche tostada"],
  ["ceviche", "ceviche"],
  ["ceviche de camar\xf3n", "shrimp ceviche"],
  ["coctel de camar\xf3n", "shrimp cocktail"],
  ["aguachile", "aguachile"],
  ["elote", "street corn"],
  ["esquites", "esquites"],
  ["churros", "churros"],
  ["flan", "flan"],
  ["tres leches", "tres leches cake"],
  ["arroz con leche", "rice pudding"],
  ["pan dulce", "sweet bread"],
  ["concha", "concha"],
  ["empanada", "empanada"],
  ["empanadas", "empanadas"],
  ["arepa", "arepa"],
  ["arepas", "arepas"],
  ["pupusa", "pupusa"],
  ["pupusas", "pupusas"],
  ["baleada", "baleada"],
  ["yuca frita", "fried yuca"],
  ["pl\xe1tanos maduros", "sweet plantains"],
  ["tostones", "tostones"],
  ["mofongo", "mofongo"],
  ["ropa vieja", "ropa vieja"],
  ["arroz con pollo", "chicken and rice"],
  ["arroz con gandules", "rice with pigeon peas"],
  ["pernil", "roast pork"],
  ["lech\xf3n", "roast pork"],
  ["pollo asado", "grilled chicken"],
  ["carne asada", "carne asada"],
  ["milanesa", "breaded cutlet"],
  ["torta", "torta"],
  ["torta de milanesa", "milanesa torta"],
  ["pambazo", "pambazo"],
  ["cemita", "cemita"],
  ["caldo de res", "beef soup"],
  ["caldo de pollo", "chicken soup"],
  ["caldo de mariscos", "seafood soup"],
  ["sopa de tortilla", "tortilla soup"],
  ["sopa de fideo", "fideo soup"],
  ["frijoles charros", "charro beans"],
  ["frijoles refritos", "refried beans"],
  ["arroz mexicano", "Mexican rice"],
  ["pico de gallo", "pico de gallo"],
  ["guacamole", "guacamole"],
  ["salsa verde", "green salsa"],
  ["salsa roja", "red salsa"],
  ["salsa picante", "hot salsa"],
  ["jalape\xf1o", "jalapeno"],
  ["rajas", "pepper strips"],
  ["nopales", "cactus paddles"],
  ["chorizo", "chorizo"],
  ["al pastor", "al pastor pork"],
  ["carnitas", "carnitas"],
  ["barbacoa", "barbacoa"],
  ["agua fresca", "agua fresca"],
  ["agua de horchata", "horchata"],
  ["agua de jamaica", "hibiscus agua fresca"],
  ["agua de tamarindo", "tamarind agua fresca"],
  ["horchata", "horchata"],
  ["jamaica", "hibiscus drink"],
  ["tamarindo", "tamarind drink"],
  ["atole", "atole"],
  ["champurrado", "champurrado"],
  ["caf\xe9 de olla", "spiced coffee"],
  ["chocolate caliente", "hot chocolate"],
  ["licuado", "fruit smoothie"],
  ["mangonada", "mangonada"],
  ["michelada", "michelada"],
  ["margarita", "margarita"],
] as const;

const koreanSourceOfferTermsToEnglish = [
  ["\uae40\uce58\ucc0c\uac1c", "kimchi stew"],
  ["\ub41c\uc7a5\ucc0c\uac1c", "soybean paste stew"],
  ["\uc21c\ub450\ubd80\ucc0c\uac1c", "soft tofu stew"],
  ["\ubd80\ub300\ucc0c\uac1c", "army stew"],
  ["\uccad\uad6d\uc7a5", "fermented soybean stew"],
  ["\uac08\ube44\ud0d5", "short rib soup"],
  ["\uc124\ub801\ud0d5", "ox bone soup"],
  ["\uc0bc\uacc4\ud0d5", "ginseng chicken soup"],
  ["\uac10\uc790\ud0d5", "pork bone soup"],
  ["\uc721\uac1c\uc7a5", "spicy beef soup"],
  ["\ubbf8\uc5ed\uad6d", "seaweed soup"],
  ["\ub5a1\uad6d", "rice cake soup"],
  ["\ub9cc\ub463\uad6d", "dumpling soup"],
  ["\ub0c9\uba74", "cold noodles"],
  ["\ubb3c\ub0c9\uba74", "cold buckwheat noodles"],
  ["\ube44\ube54\ub0c9\uba74", "spicy cold noodles"],
  ["\ube44\ube54\ubc25", "bibimbap"],
  ["\ub3cc\uc1a5\ube44\ube54\ubc25", "stone bowl bibimbap"],
  ["\ubd88\uace0\uae30", "bulgogi"],
  ["\uc81c\uc721\ubcf6\uc74c", "spicy pork stir-fry"],
  ["\ub2ed\uac08\ube44", "spicy stir-fried chicken"],
  ["\uac08\ube44\ucc1c", "braised short ribs"],
  ["\ub3fc\uc9c0\uac08\ube44", "pork ribs"],
  ["\uc0bc\uacb9\uc0b4", "pork belly"],
  ["\ubcf4\uc308", "bossam"],
  ["\uc871\ubc1c", "jokbal"],
  ["\uae40\ubc25", "gimbap"],
  ["\ucc38\uce58\uae40\ubc25", "tuna gimbap"],
  ["\uc57c\ucc44\uae40\ubc25", "vegetable gimbap"],
  ["\ub5a1\ubcf6\uc774", "tteokbokki"],
  ["\ub77c\ubcf6\uc774", "rabokki"],
  ["\uc21c\ub300", "blood sausage"],
  ["\uc5b4\ubb35", "fish cake"],
  ["\uc624\ub385", "fish cake skewers"],
  ["\ud280\uae40", "fried snacks"],
  ["\uae40\uce58\uc804", "kimchi pancake"],
  ["\ud574\ubb3c\ud30c\uc804", "seafood scallion pancake"],
  ["\ud30c\uc804", "scallion pancake"],
  ["\uac10\uc790\uc804", "potato pancake"],
  ["\ube48\ub300\ub5a1", "mung bean pancake"],
  ["\uc7a1\ucc44", "japchae"],
  ["\ub9cc\ub450", "dumplings"],
  ["\uad70\ub9cc\ub450", "fried dumplings"],
  ["\ucc10\ub9cc\ub450", "steamed dumplings"],
  ["\ucc1c\ub2ed", "braised chicken"],
  ["\ub2ed\uac15\uc815", "crispy sweet chicken"],
  ["\uc591\ub150\uce58\ud0a8", "spicy fried chicken"],
  ["\ud6c4\ub77c\uc774\ub4dc\uce58\ud0a8", "fried chicken"],
  ["\uac04\uc7a5\uce58\ud0a8", "soy garlic chicken"],
  ["\uce58\ud0a8", "Korean fried chicken"],
  ["\uce58\uc988\ubcfc", "cheese balls"],
  ["\ucf58\uce58\uc988", "corn cheese"],
  ["\uacc4\ub780\ucc1c", "steamed egg"],
  ["\uacc4\ub780\ub9d0\uc774", "rolled omelet"],
  ["\uae40\uce58\ubcf6\uc74c\ubc25", "kimchi fried rice"],
  ["\ubcf6\uc74c\ubc25", "fried rice"],
  ["\uc624\ubbc0\ub77c\uc774\uc2a4", "omelet rice"],
  ["\ub3c8\uae4c\uc2a4", "pork cutlet"],
  ["\uce58\uc988\ub3c8\uae4c\uc2a4", "cheese pork cutlet"],
  ["\uce74\ub808\ub77c\uc774\uc2a4", "curry rice"],
  ["\uc9dc\uc7a5\uba74", "black bean noodles"],
  ["\uc9ec\ubf55", "spicy seafood noodle soup"],
  ["\ud0d5\uc218\uc721", "sweet and sour pork"],
  ["\ub9c8\ub77c\ud0d5", "malatang"],
  ["\uce7c\uad6d\uc218", "knife-cut noodle soup"],
  ["\uc218\uc81c\ube44", "hand-pulled dough soup"],
  ["\uc794\uce58\uad6d\uc218", "banquet noodles"],
  ["\ube44\ube54\uad6d\uc218", "spicy mixed noodles"],
  ["\ucf69\uad6d\uc218", "cold soybean noodles"],
  ["\uae40\uce58", "kimchi"],
  ["\uae4d\ub450\uae30", "cubed radish kimchi"],
  ["\uc624\uc774\uc18c\ubc15\uc774", "stuffed cucumber kimchi"],
  ["\ub098\ubb3c", "seasoned vegetables"],
  ["\ucf69\ub098\ubb3c", "seasoned bean sprouts"],
  ["\ud638\ub5a1", "hotteok"],
  ["\ubd95\uc5b4\ube75", "fish-shaped pastry"],
  ["\ud638\ube75", "steamed bun"],
  ["\ucc10\ube75", "steamed bun"],
  ["\uc57d\uacfc", "honey cookie"],
  ["\uc1a1\ud3b8", "songpyeon"],
  ["\ub5a1", "rice cake"],
  ["\uc778\uc808\ubbf8", "injeolmi"],
  ["\ube59\uc218", "shaved ice"],
  ["\ud325\ube59\uc218", "red bean shaved ice"],
  ["\ud638\ub450\uacfc\uc790", "walnut cakes"],
  ["\ub2ec\uace0\ub098", "dalgona candy"],
  ["\uc57d\uc2dd", "sweet rice dessert"],
  ["\uc2dd\ud61c", "sweet rice punch"],
  ["\uc218\uc815\uacfc", "cinnamon punch"],
  ["\ubcf4\ub9ac\ucc28", "barley tea"],
  ["\uc625\uc218\uc218\ucc28", "corn tea"],
  ["\uc720\uc790\ucc28", "citron tea"],
  ["\ub300\ucd94\ucc28", "jujube tea"],
  ["\ub9e4\uc2e4\ucc28", "plum tea"],
  ["\ub9c9\uac78\ub9ac", "makgeolli"],
  ["\uc18c\uc8fc", "soju"],
  ["\ubcf5\ubd84\uc790\uc8fc", "raspberry wine"],
  ["\ubc14\ub098\ub098\uc6b0\uc720", "banana milk"],
  ["\ub538\uae30\uc6b0\uc720", "strawberry milk"],
  ["\ubbf8\uc22b\uac00\ub8e8", "multigrain shake"],
] as const;

describe("localized offer terms", () => {
  it("covers 100 common generic offer terms in Spanish and Korean", () => {
    expect(commonOfferTerms).toHaveLength(100);

    for (const sourceDisplayName of commonOfferTerms) {
      for (const locale of ["es-US", "ko-KR"] as const) {
        const term = resolveLocalizedOfferTerm({ sourceDisplayName, locale });

        expect({
          sourceDisplayName,
          locale,
          source: term.source,
          verificationStatus: term.verificationStatus,
          approvedLocalizedName: term.approvedLocalizedName,
          doNotTranslate: term.doNotTranslate,
        }).toEqual({
          sourceDisplayName,
          locale,
          source: "reviewed_dictionary",
          verificationStatus: "verified",
          approvedLocalizedName: true,
          doNotTranslate: false,
        });
        expect(term.displayName.trim().length).toBeGreaterThan(0);
      }
    }
  });

  it("covers 100 popular Spanish-language food and drink source terms in English", () => {
    expect(spanishSourceOfferTermsToEnglish).toHaveLength(100);

    for (const [sourceDisplayName, englishDisplayName] of spanishSourceOfferTermsToEnglish) {
      const term = resolveLocalizedOfferTerm({ sourceDisplayName, locale: "en-US" });

      expect({
        sourceDisplayName,
        displayName: term.displayName,
        source: term.source,
        verificationStatus: term.verificationStatus,
        approvedLocalizedName: term.approvedLocalizedName,
        doNotTranslate: term.doNotTranslate,
      }).toEqual({
        sourceDisplayName,
        displayName: englishDisplayName,
        source: "reviewed_dictionary",
        verificationStatus: "verified",
        approvedLocalizedName: true,
        doNotTranslate: false,
      });
    }
  });

  it("covers 100 popular Korean food and drink source terms in English", () => {
    expect(koreanSourceOfferTermsToEnglish).toHaveLength(100);

    for (const [sourceDisplayName, englishDisplayName] of koreanSourceOfferTermsToEnglish) {
      const term = resolveLocalizedOfferTerm({ sourceDisplayName, locale: "en-US" });

      expect({
        sourceDisplayName,
        displayName: term.displayName,
        source: term.source,
        verificationStatus: term.verificationStatus,
        approvedLocalizedName: term.approvedLocalizedName,
        doNotTranslate: term.doNotTranslate,
      }).toEqual({
        sourceDisplayName,
        displayName: englishDisplayName,
        source: "reviewed_dictionary",
        verificationStatus: "verified",
        approvedLocalizedName: true,
        doNotTranslate: false,
      });
    }
  });
});
