#!/usr/bin/env bash
#
# App Store screenshot capture pipeline (macOS only).
#
# Boots an iOS Simulator whose NATIVE resolution is exactly 1320x2868
# (iPhone 6.9" — iPhone 16 Pro Max / iPhone 17 Pro Max), pins the status bar to
# the App Store look (9:41, full battery/wifi/cellular), runs the ScreenshotTests
# UI test, extracts the XCTAttachments into fastlane/screenshots/en-US/ with
# numbered filenames (which control App Store ordering), strips alpha, and fails
# loudly if any output is not EXACTLY 1320x2868.
#
# We never resize an image. If a capture is the wrong size, the fix is the device
# choice, not the pixels — the preflight below enforces that before any work.
#
# Requirements on the runner:
#   - Xcode + iOS Simulator
#   - xcparse   (brew install chargepoint/xcparse/xcparse)   for .xcresult extraction
#   - pngcrush  (ships with the Xcode toolchain)             for alpha stripping
#   - The native iOS project generated by `expo prebuild -p ios` with the
#     ScreenshotTests target added (see docs/screenshots/SETUP.md).

set -euo pipefail

# ── Config (override via env) ────────────────────────────────────────────────
DEVICE="${SCREENSHOT_DEVICE:-iPhone 16 Pro Max}"       # must be a 6.9" 1320x2868 device
SCHEME="${SCREENSHOT_SCHEME:-ScreenshotTests}"        # dedicated scheme from the config plugin
TEST_TARGET="${SCREENSHOT_TEST_TARGET:-ScreenshotTests}"
EXPECT_W=1320
EXPECT_H=2868

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKSPACE="$(ls -d "$ROOT"/ios/*.xcworkspace 2>/dev/null | head -n1 || true)"
OUT_DIR="$ROOT/fastlane/screenshots/en-US"
WORK_DIR="$ROOT/.screenshots-work"
RESULT_BUNDLE="$WORK_DIR/Screenshots.xcresult"

fail() { echo "❌ $*" >&2; exit 1; }
note() { echo "▶ $*"; }

# ── Preflight: tools ─────────────────────────────────────────────────────────
[ -n "$WORKSPACE" ] || fail "No ios/*.xcworkspace found. Run 'expo prebuild -p ios' first (see docs/screenshots/SETUP.md)."
command -v xcparse  >/dev/null || fail "xcparse not found. Install: brew install chargepoint/xcparse/xcparse"
command -v pngcrush >/dev/null || fail "pngcrush not found (part of the Xcode toolchain). Install Xcode command line tools."
command -v sips     >/dev/null || fail "sips not found — this script must run on macOS."

rm -rf "$WORK_DIR"; mkdir -p "$WORK_DIR" "$OUT_DIR"

# ── Boot the simulator ───────────────────────────────────────────────────────
note "Booting simulator: $DEVICE"
UDID="$(xcrun simctl list devices available | grep -F "$DEVICE (" | head -n1 | grep -Eo '[0-9A-F-]{36}' || true)"
[ -n "$UDID" ] || fail "Simulator '$DEVICE' not available. List with: xcrun simctl list devices available"
xcrun simctl boot "$UDID" 2>/dev/null || true
xcrun simctl bootstatus "$UDID" -b

# ── Preflight: confirm the DEVICE renders exactly 1320x2868 ──────────────────
# This is the "confirm the device, don't resize the image" gate. We take a raw
# device screenshot and check its native pixel size BEFORE running the tests.
note "Verifying device native resolution with sips"
PREFLIGHT="$WORK_DIR/preflight.png"
xcrun simctl io "$UDID" screenshot "$PREFLIGHT" >/dev/null
PW="$(sips -g pixelWidth  "$PREFLIGHT" | awk '/pixelWidth/{print $2}')"
PH="$(sips -g pixelHeight "$PREFLIGHT" | awk '/pixelHeight/{print $2}')"
if [ "$PW" != "$EXPECT_W" ] || [ "$PH" != "$EXPECT_H" ]; then
  fail "Device '$DEVICE' renders ${PW}x${PH}, not ${EXPECT_W}x${EXPECT_H}.
       Pick a 6.9\" device (iPhone 16 Pro Max or iPhone 17 Pro Max):
         SCREENSHOT_DEVICE='iPhone 17 Pro Max' $0
       Do NOT resize — change the device."
fi
note "Device confirmed at ${PW}x${PH} ✓"

# ── Status bar override: the App Store look ──────────────────────────────────
note "Overriding status bar (9:41, full battery/wifi/cellular)"
xcrun simctl status_bar "$UDID" override \
  --time "9:41" \
  --dataNetwork wifi \
  --wifiMode active --wifiBars 3 \
  --cellularMode active --cellularBars 4 \
  --batteryState charged --batteryLevel 100

# ── Run the UI test ──────────────────────────────────────────────────────────
note "Running $TEST_TARGET"
set -x
xcodebuild test \
  -workspace "$WORKSPACE" \
  -scheme "$SCHEME" \
  -destination "platform=iOS Simulator,id=$UDID" \
  -only-testing:"$TEST_TARGET" \
  -resultBundlePath "$RESULT_BUNDLE" \
  -parallel-testing-enabled NO \
  CODE_SIGNING_ALLOWED=NO | xcpretty || { set +x; fail "xcodebuild test failed."; }
set +x

# ── Extract attachments ──────────────────────────────────────────────────────
note "Extracting attachments from .xcresult"
RAW_DIR="$WORK_DIR/raw"; mkdir -p "$RAW_DIR"
xcparse screenshots --test "$RESULT_BUNDLE" "$RAW_DIR"

# The UI test names each attachment "NN_screen" (e.g. 01_deal_feed). xcparse may
# append a suffix; we keep only shots whose name starts with NN_ and normalize to
# fastlane's numbered filename so App Store ordering is deterministic.
shopt -s globstar nullglob
found=0
for src in "$RAW_DIR"/**/*.png; do
  base="$(basename "$src")"
  if [[ "$base" =~ ^([0-9]{2}_[a-zA-Z0-9_-]+) ]]; then
    dest="$OUT_DIR/${BASH_REMATCH[1]}.png"
    cp "$src" "$dest"
    found=$((found+1))
  fi
done
[ "$found" -gt 0 ] || fail "No numbered screenshots (NN_name.png) found in the .xcresult. Check attachment names in ScreenshotTests."
note "Collected $found screenshot(s)"

# ── Strip alpha + verify exact dimensions ────────────────────────────────────
note "Stripping alpha and verifying every file is exactly ${EXPECT_W}x${EXPECT_H}"
bad=0
for f in "$OUT_DIR"/*.png; do
  pngcrush -q -ow -rem alpha "$f" || fail "pngcrush failed on $f"
  W="$(sips -g pixelWidth  "$f" | awk '/pixelWidth/{print $2}')"
  H="$(sips -g pixelHeight "$f" | awk '/pixelHeight/{print $2}')"
  if [ "$W" != "$EXPECT_W" ] || [ "$H" != "$EXPECT_H" ]; then
    echo "   ✗ $(basename "$f") is ${W}x${H}" >&2
    bad=$((bad+1))
  else
    echo "   ✓ $(basename "$f") ${W}x${H}"
  fi
done
[ "$bad" -eq 0 ] || fail "$bad file(s) are not exactly ${EXPECT_W}x${EXPECT_H}. Aborting — do not upload."

# ── Reset status bar ─────────────────────────────────────────────────────────
xcrun simctl status_bar "$UDID" clear || true

echo "✅ $found screenshot(s) ready in $OUT_DIR (all ${EXPECT_W}x${EXPECT_H}, alpha stripped)"
