(() => {
  const STORAGE_KEY = "twofer_site_locale";
  const SUPPORTED = ["en", "es", "ko"];

  const messages = {
    en: {
      "site.lang.en": "EN",
      "site.lang.es": "ES",
      "site.lang.ko": "KO",
      "nav.menu": "Menu",
      "nav.getApp": "Get the App",
      "nav.customers": "For Customers",
      "nav.businesses": "For Businesses",
      "nav.how": "How It Works",
      "nav.support": "Support",
      "nav.deleteAccount": "Delete account",
      "nav.businessAccess": "Business Access",
      "nav.businessTerms": "Business Terms",
      "nav.businessTrial": "Request Business Access",
      "home.title": "Twofer - Live Local Specials",
      "home.meta": "Twofer helps local businesses create live 2-for-1 and deep-discount specials, publish nearby, and redeem in store by QR code. Live now in DFW.",
      "home.status": "Live now in Dallas-Fort Worth",
      "home.hero": "Live local <span>specials</span> for slow hours.",
      "home.lede": "Twofer is like an on-demand happy hour engine for local businesses: create a 2-for-1 or 40%+ off promotion with AI, publish it nearby, and redeem customers in store by QR code.",
      "home.availability": "Free for iPhone and Android. New business accounts are reviewed before they can publish.",
      "home.flowTitle": "See how it works",
      "home.flowText": "Browse a sample special below, then open the app to claim real offers nearby, share with a friend, and redeem in store with a QR code.",
      "home.nearbyNow": "Nearby now",
      "home.sample": "Sample",
      "home.offerCroissants": "2-for-1 croissants",
      "home.offerColdBrew": "40% off cold brew",
      "home.customersEyebrow": "For customers",
      "home.customersTitle": "Discover live local specials before they disappear",
      "home.customersBody": "Find nearby 2-for-1, free-item, and deep-discount offers, claim from your phone, share with a friend, and redeem in store.",
      "home.freeCustomers": "Free for customers.",
      "home.findTitle": "Find Live Specials",
      "home.findBody": "See timely offers from local cafes, bakeries, coffee shops, and more.",
      "home.realtimeTitle": "Real-Time Updates",
      "home.realtimeBody": "Sort by time, distance, availability, and location before the offer expires.",
      "home.localTitle": "Support Local",
      "home.localBody": "Try nearby businesses while helping local owners fill slow hours.",
      "home.businessEyebrow": "For businesses",
      "home.businessTitle": "An on-demand happy hour tool for slow hours",
      "home.businessBody": "Create 2-for-1, free-item, or 40%+ off specials in under 2 minutes. You control the window, quantity, terms, and when it goes live.",
      "home.generateTitle": "Generate the Ad",
      "home.generateBody": "Upload a photo or describe the item; AI drafts clear promotion copy you can edit.",
      "home.reachTitle": "Reach Nearby Customers",
      "home.reachBody": "Show timely specials to people already looking nearby.",
      "home.controlTitle": "Control the Offer",
      "home.controlBody": "Set the time window, quantity, terms, and pause or publish status.",
      "home.accessTitle": "Reviewed Before You Publish",
      "home.accessBody": "New business accounts are reviewed before publishing goes live.",
      "home.ownBusiness": "Own or manage a local business?",
      "home.ownBusinessBody": "New business accounts are reviewed before they can publish. Submit a business access request below or contact support@twoferapp.com.",
      "home.promoKicker": "AI-assisted promotion setup",
      "home.promoText": "Describe the item, review the ad, publish the special",
      "home.howTitle": "How Twofer Works",
      "home.step1Title": "Create a live special",
      "home.step1Body": "Approved businesses describe an item or upload a photo, then AI drafts editable promotion copy.",
      "home.step2Title": "Set the controls",
      "home.step2Body": "Choose the offer type, time window, quantity, and terms before publishing.",
      "home.step3Title": "Claim and redeem",
      "home.step3Body": "Nearby customers claim in the app, share with a friend, and redeem in store with a QR code.",
      "home.faqTitle": "Frequently Asked Questions",
      "home.faqQ1": "What is Twofer?",
      "home.faqA1": "Twofer is a live local specials app for customers and an AI-assisted promotion tool for local businesses.",
      "home.faqQ2": "Are the specials real?",
      "home.faqA2": "Yes. The two cards on this page are illustrated samples; open the app to see live specials near you.",
      "home.faqQ3": "Why do businesses need to be approved?",
      "home.faqA3": "New business accounts are reviewed to keep published specials tied to real local businesses.",
      "home.faqQ4": "What kinds of promotions can businesses create?",
      "home.faqA4": "Businesses can create 2-for-1, free-item, and deep-discount offers with controlled time windows and quantities.",
      "home.faqQ5": "Is Twofer free for customers?",
      "home.faqA5": "Yes. Twofer is free for customers.",
      "home.faqQ6": "Where is Twofer available?",
      "home.faqA6": "Twofer is live in the Dallas-Fort Worth area, with more cities planned.",
      "home.footerBody1": "Live local specials for customers, with AI promotion tools and QR redemption controls for local businesses.",
      "home.footerBody2": "Live now in DFW. Customer access is open; new business accounts are reviewed before they publish.",
      "site.privacy": "Privacy Policy",
      "site.terms": "Terms of Service",
      "trial.title": "Request DFW Business Access | Twofer",
      "trial.meta": "Request reviewed Twofer business access in Dallas-Fort Worth.",
      "trial.kicker": "DFW business access",
      "trial.heading": "Request DFW Business Access",
      "trial.lede": "New business accounts are reviewed before they publish. Tell us about your local business and we will route your DFW business access request to the right onboarding path.",
      "trial.panelTitle": "For businesses",
      "trial.panelBody": "Twofer helps approved local businesses create limited-time 2-for-1, free-item, and deep-discount specials for slow hours. You control the offer window, quantity, terms, and publish status.",
      "trial.bullet1": "AI-assisted offer copy that you review before publishing.",
      "trial.bullet2": "QR-code redemption in store.",
      "trial.bullet3": "Reviewed business access, typically within 1-2 business days.",
      "trial.name": "Business name",
      "trial.contact": "Owner or manager name",
      "trial.email": "Business email",
      "trial.phone": "Phone number",
      "trial.address": "Business address",
      "trial.type": "Business type",
      "trial.typeEmpty": "Select one",
      "trial.coffee": "Coffee shop",
      "trial.cafe": "Cafe",
      "trial.bakery": "Bakery",
      "trial.restaurant": "Restaurant",
      "trial.other": "Other local business",
      "trial.web": "Website or Instagram",
      "trial.slow": "Best slow hours",
      "trial.promote": "What would you like to promote?",
      "trial.launch": "Launch area confirmation",
      "trial.launchPlaceholder": "Example: Dallas, Oak Cliff, Bishop Arts",
      "trial.honeypot": "Company website",
      "trial.terms": "I accept the",
      "trial.businessTerms": "Business Terms",
      "trial.privacyLead": "I acknowledge the",
      "trial.privacyPolicy": "Privacy Policy",
      "trial.submit": "Submit access request",
      "trial.contactSupport": "Contact support",
      "trial.footer": "Business access is reviewed before activation. Checkout and subscription changes are handled only through approved web/admin billing flows.",
      "trial.validationName": "Enter your business name.",
      "trial.validationContact": "Enter the owner or manager name.",
      "trial.validationEmail": "Enter a valid business email.",
      "trial.validationTerms": "Please accept the Business Terms.",
      "trial.validationPrivacy": "Please acknowledge the Privacy Policy.",
      "trial.submitting": "Submitting...",
      "trial.failure": "We could not submit the request. Please contact support@twoferapp.com.",
      "businessRedirect.title": "Business Access | Twofer",
      "businessRedirect.heading": "Business access requests moved",
      "businessRedirect.body": "Opening the current Twofer business access request page.",
      "businessRedirect.cta": "Continue to business access",
    },
    es: {
      "site.lang.en": "EN",
      "site.lang.es": "ES",
      "site.lang.ko": "KO",
      "nav.menu": "Menu",
      "nav.getApp": "Obtener la app",
      "nav.customers": "Clientes",
      "nav.businesses": "Negocios",
      "nav.how": "Como funciona",
      "nav.support": "Soporte",
      "nav.deleteAccount": "Eliminar cuenta",
      "nav.businessAccess": "Acceso de negocio",
      "nav.businessTerms": "Terminos para negocios",
      "nav.businessTrial": "Solicitar acceso",
      "home.title": "Twofer - Ofertas locales en vivo",
      "home.meta": "Twofer ayuda a negocios locales a crear ofertas 2x1 y descuentos profundos, publicarlas cerca y redimirlas en tienda con codigo QR. En vivo ahora en DFW.",
      "home.status": "En vivo ahora en Dallas-Fort Worth",
      "home.hero": "<span>Ofertas</span> locales en vivo para horas lentas.",
      "home.lede": "Twofer es como un motor de happy hour bajo demanda para negocios locales: crea una promocion 2x1 o de 40%+ con IA, publicala cerca y redime clientes en tienda con codigo QR.",
      "home.availability": "Gratis para iPhone y Android. Las nuevas cuentas de negocio se revisan antes de publicar.",
      "home.flowTitle": "Mira como funciona",
      "home.flowText": "Explora una oferta de muestra, luego abre la app para reclamar ofertas reales cercanas, compartir con un amigo y redimir en tienda con codigo QR.",
      "home.nearbyNow": "Cerca ahora",
      "home.sample": "Muestra",
      "home.offerCroissants": "Croissants 2x1",
      "home.offerColdBrew": "40% de descuento en cold brew",
      "home.customersEyebrow": "Para clientes",
      "home.customersTitle": "Descubre ofertas locales antes de que desaparezcan",
      "home.customersBody": "Encuentra ofertas cercanas 2x1, articulos gratis y descuentos profundos, reclamala desde tu telefono, comparte con un amigo y redime en tienda.",
      "home.freeCustomers": "Gratis para clientes.",
      "home.findTitle": "Encuentra ofertas en vivo",
      "home.findBody": "Ve ofertas oportunas de cafes, panaderias, cafeterias y mas negocios locales.",
      "home.realtimeTitle": "Actualizaciones en tiempo real",
      "home.realtimeBody": "Ordena por hora, distancia, disponibilidad y ubicacion antes de que expire la oferta.",
      "home.localTitle": "Apoya lo local",
      "home.localBody": "Prueba negocios cercanos mientras ayudas a duenos locales a llenar horas lentas.",
      "home.businessEyebrow": "Para negocios",
      "home.businessTitle": "Una herramienta de happy hour bajo demanda para horas lentas",
      "home.businessBody": "Crea ofertas 2x1, articulos gratis o descuentos de 40%+ en menos de 2 minutos. Tu controlas la ventana, cantidad, terminos y cuando se publica.",
      "home.generateTitle": "Genera el anuncio",
      "home.generateBody": "Sube una foto o describe el articulo; la IA redacta texto promocional claro que puedes editar.",
      "home.reachTitle": "Llega a clientes cercanos",
      "home.reachBody": "Muestra ofertas oportunas a personas que ya estan buscando cerca.",
      "home.controlTitle": "Controla la oferta",
      "home.controlBody": "Define horario, cantidad, terminos y pausa o estado de publicacion.",
      "home.accessTitle": "Revisado antes de publicar",
      "home.accessBody": "Las nuevas cuentas de negocio se revisan antes de que la publicacion este activa.",
      "home.ownBusiness": "Tienes o administras un negocio local?",
      "home.ownBusinessBody": "Las nuevas cuentas de negocio se revisan antes de poder publicar. Envia una solicitud de acceso de negocio abajo o contacta support@twoferapp.com.",
      "home.promoKicker": "Configuracion de promocion con IA",
      "home.promoText": "Describe el articulo, revisa el anuncio y publica la oferta",
      "home.howTitle": "Como funciona Twofer",
      "home.step1Title": "Crea una oferta en vivo",
      "home.step1Body": "Negocios aprobados describen un articulo o suben una foto, y la IA redacta texto promocional editable.",
      "home.step2Title": "Configura los controles",
      "home.step2Body": "Elige tipo de oferta, horario, cantidad y terminos antes de publicar.",
      "home.step3Title": "Reclama y redime",
      "home.step3Body": "Clientes cercanos reclaman en la app, comparten con un amigo y redimen en tienda con codigo QR.",
      "home.faqTitle": "Preguntas frecuentes",
      "home.faqQ1": "Que es Twofer?",
      "home.faqA1": "Twofer es una app de ofertas locales en vivo para clientes y una herramienta de promocion con IA para negocios locales.",
      "home.faqQ2": "Las ofertas son reales ahora?",
      "home.faqA2": "Si. Las dos tarjetas en esta pagina son muestras ilustradas; abre la app para ver ofertas en vivo cerca de ti.",
      "home.faqQ3": "Por que los negocios necesitan aprobacion?",
      "home.faqA3": "Las nuevas cuentas de negocio se revisan para mantener las ofertas publicadas conectadas con negocios locales reales.",
      "home.faqQ4": "Que promociones pueden crear los negocios?",
      "home.faqA4": "Los negocios pueden crear ofertas 2x1, articulos gratis y descuentos profundos con horarios y cantidades controladas.",
      "home.faqQ5": "Twofer es gratis para clientes?",
      "home.faqA5": "Si. Twofer es gratis para clientes.",
      "home.faqQ6": "Donde esta disponible Twofer?",
      "home.faqA6": "Twofer esta en vivo en Dallas-Fort Worth, con mas ciudades planeadas.",
      "home.footerBody1": "Ofertas locales en vivo para clientes, con herramientas de promocion con IA y redencion QR para negocios locales.",
      "home.footerBody2": "En vivo ahora en DFW. El acceso para clientes esta abierto; las nuevas cuentas de negocio se revisan antes de publicar.",
      "site.privacy": "Politica de privacidad",
      "site.terms": "Terminos de servicio",
      "trial.title": "Solicita acceso de negocio en DFW | Twofer",
      "trial.meta": "Solicita acceso revisado de Twofer para negocios en Dallas-Fort Worth.",
      "trial.kicker": "Acceso de negocio en DFW",
      "trial.heading": "Solicita acceso de negocio en DFW",
      "trial.lede": "Las nuevas cuentas de negocio se revisan antes de publicar. Cuentanos sobre tu negocio local y enviaremos tu solicitud de acceso en DFW al camino correcto de onboarding.",
      "trial.panelTitle": "Para negocios",
      "trial.panelBody": "Twofer ayuda a negocios locales aprobados a crear ofertas 2x1, articulos gratis y descuentos profundos por tiempo limitado para horas lentas. Tu controlas horario, cantidad, terminos y estado de publicacion.",
      "trial.bullet1": "Texto de oferta con IA que revisas antes de publicar.",
      "trial.bullet2": "Redencion con codigo QR en tienda.",
      "trial.bullet3": "Acceso de negocio revisado, normalmente en 1-2 dias habiles.",
      "trial.name": "Nombre del negocio",
      "trial.contact": "Nombre del dueno o gerente",
      "trial.email": "Email del negocio",
      "trial.phone": "Telefono",
      "trial.address": "Direccion del negocio",
      "trial.type": "Tipo de negocio",
      "trial.typeEmpty": "Selecciona uno",
      "trial.coffee": "Cafeteria",
      "trial.cafe": "Cafe",
      "trial.bakery": "Panaderia",
      "trial.restaurant": "Restaurante",
      "trial.other": "Otro negocio local",
      "trial.web": "Sitio web o Instagram",
      "trial.slow": "Mejores horas lentas",
      "trial.promote": "Que te gustaria promocionar?",
      "trial.launch": "Confirmacion del area de lanzamiento",
      "trial.launchPlaceholder": "Ejemplo: Dallas, Oak Cliff, Bishop Arts",
      "trial.honeypot": "Sitio web de la empresa",
      "trial.terms": "Acepto los",
      "trial.businessTerms": "Terminos para negocios",
      "trial.privacyLead": "Reconozco la",
      "trial.privacyPolicy": "Politica de privacidad",
      "trial.submit": "Enviar solicitud de acceso",
      "trial.contactSupport": "Contactar soporte",
      "trial.footer": "El acceso de negocio se revisa antes de activarse. El checkout y los cambios de suscripcion se manejan solo mediante flujos web/admin aprobados.",
      "trial.validationName": "Ingresa el nombre de tu negocio.",
      "trial.validationContact": "Ingresa el nombre del dueno o gerente.",
      "trial.validationEmail": "Ingresa un email de negocio valido.",
      "trial.validationTerms": "Acepta los Terminos para negocios.",
      "trial.validationPrivacy": "Reconoce la Politica de privacidad.",
      "trial.submitting": "Enviando...",
      "trial.failure": "No pudimos enviar la solicitud. Contacta support@twoferapp.com.",
      "businessRedirect.title": "Acceso de negocio | Twofer",
      "businessRedirect.heading": "Las solicitudes de acceso se movieron",
      "businessRedirect.body": "Abriendo la pagina actual de solicitud de acceso para negocios.",
      "businessRedirect.cta": "Continuar a acceso de negocio",
    },
    ko: {
      "site.lang.en": "EN",
      "site.lang.es": "ES",
      "site.lang.ko": "KO",
      "nav.menu": "메뉴",
      "nav.getApp": "앱 받기",
      "nav.customers": "고객용",
      "nav.businesses": "비즈니스용",
      "nav.how": "이용 방법",
      "nav.support": "지원",
      "nav.deleteAccount": "계정 삭제",
      "nav.businessAccess": "비즈니스 액세스",
      "nav.businessTerms": "비즈니스 약관",
      "nav.businessTrial": "비즈니스 액세스 요청",
      "home.title": "Twofer - 실시간 지역 특가",
      "home.meta": "Twofer는 지역 비즈니스가 실시간 2-for-1 및 큰 할인 특가를 만들고, 가까운 고객에게 공개하고, 매장에서 QR 코드로 리딤할 수 있게 돕습니다. DFW에서 지금 이용할 수 있습니다.",
      "home.status": "Dallas-Fort Worth에서 이용 가능",
      "home.hero": "한가한 시간대를 위한 실시간 지역 <span>특가</span>.",
      "home.lede": "Twofer는 지역 비즈니스를 위한 온디맨드 해피아워 도구입니다. AI로 2-for-1 또는 40% 이상 할인 프로모션을 만들고, 근처에 공개한 뒤, 매장에서 QR 코드로 고객을 리딤하세요.",
      "home.availability": "iPhone과 Android에서 무료입니다. 새 비즈니스 계정은 게시 전에 검토됩니다.",
      "home.flowTitle": "이용 방법 보기",
      "home.flowText": "아래 샘플 특가를 둘러본 다음 앱에서 근처 실제 오퍼를 클레임하고 친구와 공유하고 매장에서 QR 코드로 리딤하세요.",
      "home.nearbyNow": "지금 근처",
      "home.sample": "샘플",
      "home.offerCroissants": "크루아상 2-for-1",
      "home.offerColdBrew": "콜드브루 40% 할인",
      "home.customersEyebrow": "고객용",
      "home.customersTitle": "사라지기 전에 실시간 지역 특가를 발견하세요",
      "home.customersBody": "근처의 2-for-1, 무료 아이템, 큰 할인 오퍼를 찾고, 휴대폰에서 클레임하고, 친구와 공유한 뒤 매장에서 리딤하세요.",
      "home.freeCustomers": "고객에게 무료입니다.",
      "home.findTitle": "실시간 특가 찾기",
      "home.findBody": "지역 카페, 베이커리, 커피숍 등에서 올라오는 시간 한정 오퍼를 확인하세요.",
      "home.realtimeTitle": "실시간 업데이트",
      "home.realtimeBody": "오퍼가 만료되기 전에 시간, 거리, 재고, 위치 기준으로 정렬하세요.",
      "home.localTitle": "지역 비즈니스 응원",
      "home.localBody": "근처 비즈니스를 경험하면서 지역 사장님들이 한가한 시간을 채우도록 도와주세요.",
      "home.businessEyebrow": "비즈니스용",
      "home.businessTitle": "한가한 시간대를 위한 온디맨드 해피아워 도구",
      "home.businessBody": "2분 안에 2-for-1, 무료 아이템, 40% 이상 할인 특가를 만드세요. 공개 시간, 수량, 조건, 게시 시점을 직접 제어합니다.",
      "home.generateTitle": "광고 생성",
      "home.generateBody": "사진을 올리거나 아이템을 설명하면, AI가 편집 가능한 명확한 프로모션 문구를 초안으로 만듭니다.",
      "home.reachTitle": "근처 고객에게 도달",
      "home.reachBody": "이미 근처에서 찾고 있는 사람들에게 시간 한정 특가를 보여주세요.",
      "home.controlTitle": "오퍼 제어",
      "home.controlBody": "시간대, 수량, 조건, 일시 중지 또는 게시 상태를 설정하세요.",
      "home.accessTitle": "게시 전 검토",
      "home.accessBody": "새 비즈니스 계정은 게시가 활성화되기 전에 검토됩니다.",
      "home.ownBusiness": "지역 비즈니스를 운영하시나요?",
      "home.ownBusinessBody": "새 비즈니스 계정은 게시 전에 검토됩니다. 아래에서 비즈니스 액세스 요청을 제출하거나 support@twoferapp.com으로 문의하세요.",
      "home.promoKicker": "AI 지원 프로모션 설정",
      "home.promoText": "아이템 설명, 광고 검토, 특가 게시",
      "home.howTitle": "Twofer 이용 방법",
      "home.step1Title": "실시간 특가 만들기",
      "home.step1Body": "승인된 비즈니스가 아이템을 설명하거나 사진을 올리면, AI가 편집 가능한 프로모션 문구를 작성합니다.",
      "home.step2Title": "컨트롤 설정",
      "home.step2Body": "게시 전에 오퍼 유형, 시간대, 수량, 조건을 선택하세요.",
      "home.step3Title": "클레임하고 리딤",
      "home.step3Body": "근처 고객이 앱에서 클레임하고, 친구와 공유하고, 매장에서 QR 코드로 리딤합니다.",
      "home.faqTitle": "자주 묻는 질문",
      "home.faqQ1": "Twofer란 무엇인가요?",
      "home.faqA1": "Twofer는 고객을 위한 실시간 지역 특가 앱이자 지역 비즈니스를 위한 AI 지원 프로모션 도구입니다.",
      "home.faqQ2": "지금 오퍼가 실제인가요?",
      "home.faqA2": "네. 이 페이지의 두 카드는 예시 샘플입니다. 앱을 열어 근처의 실시간 특가를 확인하세요.",
      "home.faqQ3": "비즈니스 승인이 필요한 이유는 무엇인가요?",
      "home.faqA3": "새 비즈니스 계정은 게시된 특가가 실제 지역 비즈니스와 연결되도록 검토됩니다.",
      "home.faqQ4": "비즈니스는 어떤 프로모션을 만들 수 있나요?",
      "home.faqA4": "비즈니스는 2-for-1, 무료 아이템, 큰 할인 오퍼를 시간대와 수량을 정해 만들 수 있습니다.",
      "home.faqQ5": "Twofer는 고객에게 무료인가요?",
      "home.faqA5": "네. Twofer는 고객에게 무료입니다.",
      "home.faqQ6": "Twofer는 어디에서 이용할 수 있나요?",
      "home.faqA6": "Twofer는 Dallas-Fort Worth 지역에서 이용할 수 있으며, 더 많은 도시가 예정되어 있습니다.",
      "home.footerBody1": "고객을 위한 실시간 지역 특가, 지역 비즈니스를 위한 AI 프로모션 도구와 QR 리딤 컨트롤.",
      "home.footerBody2": "DFW에서 지금 이용할 수 있습니다. 고객 액세스는 열려 있고 새 비즈니스 계정은 게시 전에 검토됩니다.",
      "site.privacy": "개인정보 처리방침",
      "site.terms": "서비스 약관",
      "trial.title": "DFW 비즈니스 액세스 요청 | Twofer",
      "trial.meta": "Dallas-Fort Worth에서 검토되는 Twofer 비즈니스 액세스를 요청하세요.",
      "trial.kicker": "DFW 비즈니스 액세스",
      "trial.heading": "DFW 비즈니스 액세스 요청",
      "trial.lede": "새 비즈니스 계정은 게시 전에 검토됩니다. 지역 비즈니스 정보를 알려주시면 DFW 비즈니스 액세스 요청을 알맞은 온보딩 경로로 라우팅합니다.",
      "trial.panelTitle": "비즈니스용",
      "trial.panelBody": "Twofer는 승인된 지역 비즈니스가 한가한 시간대에 2-for-1, 무료 아이템, 큰 할인 특가를 제한적으로 만들 수 있게 돕습니다. 오퍼 시간, 수량, 조건, 게시 상태를 직접 제어합니다.",
      "trial.bullet1": "게시 전에 검토할 수 있는 AI 지원 오퍼 문구.",
      "trial.bullet2": "매장 QR 코드 리딤.",
      "trial.bullet3": "보통 영업일 기준 1-2일 안에 검토되는 비즈니스 액세스.",
      "trial.name": "비즈니스 이름",
      "trial.contact": "소유자 또는 매니저 이름",
      "trial.email": "비즈니스 이메일",
      "trial.phone": "전화번호",
      "trial.address": "비즈니스 주소",
      "trial.type": "비즈니스 유형",
      "trial.typeEmpty": "선택하세요",
      "trial.coffee": "커피숍",
      "trial.cafe": "카페",
      "trial.bakery": "베이커리",
      "trial.restaurant": "레스토랑",
      "trial.other": "기타 지역 비즈니스",
      "trial.web": "웹사이트 또는 Instagram",
      "trial.slow": "가장 한가한 시간대",
      "trial.promote": "무엇을 홍보하고 싶으신가요?",
      "trial.launch": "출시 지역 확인",
      "trial.launchPlaceholder": "예: Dallas, Oak Cliff, Bishop Arts",
      "trial.honeypot": "회사 웹사이트",
      "trial.terms": "다음에 동의합니다:",
      "trial.businessTerms": "비즈니스 약관",
      "trial.privacyLead": "다음을 확인했습니다:",
      "trial.privacyPolicy": "개인정보 처리방침",
      "trial.submit": "액세스 요청 보내기",
      "trial.contactSupport": "지원 문의",
      "trial.footer": "비즈니스 액세스는 활성화 전에 검토됩니다. 결제와 구독 변경은 승인된 웹/관리자 청구 흐름에서만 처리됩니다.",
      "trial.validationName": "비즈니스 이름을 입력하세요.",
      "trial.validationContact": "소유자 또는 매니저 이름을 입력하세요.",
      "trial.validationEmail": "유효한 비즈니스 이메일을 입력하세요.",
      "trial.validationTerms": "비즈니스 약관에 동의하세요.",
      "trial.validationPrivacy": "개인정보 처리방침을 확인하세요.",
      "trial.submitting": "제출 중...",
      "trial.failure": "요청을 제출하지 못했습니다. support@twoferapp.com으로 문의하세요.",
      "businessRedirect.title": "비즈니스 액세스 | Twofer",
      "businessRedirect.heading": "비즈니스 액세스 요청 페이지가 이동했습니다",
      "businessRedirect.body": "현재 Twofer 비즈니스 액세스 요청 페이지를 여는 중입니다.",
      "businessRedirect.cta": "비즈니스 액세스로 계속",
    },
  };

  Object.assign(messages.en, {
    "trial.jump": "Start request",
    "common.backHome": "Back to Twofer",
    "common.getSupport": "Get support",
    "common.businessAccess": "Business access",
    "common.questions": "Questions? Email <a href=\"mailto:support@twoferapp.com\">support@twoferapp.com</a>.",
    "support.title": "Support | Twofer",
    "support.heading": "Support",
    "support.lede": "For help with Twofer, email <a href=\"mailto:support@twoferapp.com\">support@twoferapp.com</a>.",
    "support.deleteTitle": "Account deletion",
    "support.deleteBody": "You can start account deletion from inside the Twofer app under Account or Settings. You can also contact support if you need help, or use the <a href=\"/delete-account\">delete account page</a>.",
    "support.businessTitle": "Business support",
    "support.businessBody": "Businesses can request access on the business page. Business accounts are reviewed before activation. Billing questions are handled through Twofer support and approved web/admin billing flows.",
    "support.reportTitle": "Report an offer",
    "support.reportBody": "In the app, open the offer detail screen and choose Report this offer. You can also email support with the business name, offer title, and what happened.",
    "delete.title": "Delete Account | Twofer",
    "delete.meta": "How to request deletion of your Twofer account and data.",
    "delete.heading": "Delete Account",
    "delete.lede": "You can request deletion of your Twofer account from inside the app or by contacting support.",
    "delete.appTitle": "Delete from the app",
    "delete.appBody": "Sign in to Twofer, open Account or Settings, and choose the account deletion option. The app will guide you through confirmation before deletion starts.",
    "delete.emailTitle": "Request help by email",
    "delete.emailBody": "Email <a href=\"mailto:support@twoferapp.com\">support@twoferapp.com</a> from the email address on your Twofer account and include \"Delete my Twofer account\" in the subject line.",
    "delete.retainedTitle": "What may be retained",
    "delete.retainedBody": "Some security, transaction, fraud-prevention, business, support, or legal records may be retained when required or anonymized where appropriate. Twofer does not sell personal data.",
    "terms.title": "Terms of Service | Twofer",
    "terms.heading": "Terms of Service",
    "terms.lede": "These launch terms cover consumer use of Twofer.",
    "terms.usingTitle": "Using Twofer",
    "terms.usingBody": "Twofer helps customers discover, claim, and redeem local offers. You are responsible for your account, device, and activity in the app.",
    "terms.availabilityTitle": "Offer availability",
    "terms.availabilityBody": "Offers may be time-limited, quantity-limited, location-limited, or otherwise subject to displayed terms. Availability may change before an offer is claimed.",
    "terms.redemptionTitle": "Redemption",
    "terms.redemptionBody": "Claims and QR redemption screens must be used honestly and only for eligible offers. Abuse, fraud, account sharing, or attempts to bypass limits may result in suspension.",
    "terms.limitsTitle": "Limits",
    "terms.limitsBody": "Twofer may change, pause, or discontinue features and may remove content or restrict accounts to protect customers, businesses, and the service.",
    "privacy.title": "Privacy Policy | Twofer",
    "privacy.effective": "Effective July 1, 2026",
    "privacy.heading": "Privacy Policy",
    "privacy.lede": "This policy describes the data used by the current Twofer app and website launch flow.",
    "privacy.collectTitle": "Data we collect",
    "privacy.collect1": "Account details such as name, email address, login identifiers, and role.",
    "privacy.collect2": "Consumer profile details such as ZIP code, birthday, favorites, claims, redemptions, and preferences.",
    "privacy.collect3": "Location data when you choose GPS-based nearby discovery, plus ZIP fallback preferences.",
    "privacy.collect4": "Push notification tokens and alert settings when you opt in.",
    "privacy.collect5": "Business details such as business name, address, contact person, email, phone, offer content, offer images, metrics, and staff access details where applicable.",
    "privacy.collect6": "Business access request details submitted on the website.",
    "privacy.collect7": "Usage, diagnostics, support messages, and app analytics needed to operate and improve Twofer.",
    "privacy.useTitle": "How we use data",
    "privacy.useBody": "We use data to provide account access, nearby offer discovery, claims, QR redemption, merchant tools, AI-assisted offer creation, support, abuse prevention, analytics, notifications, and legal compliance.",
    "privacy.aiTitle": "AI-assisted tools",
    "privacy.aiBody": "Business AI tools help draft offer copy and related creative materials. Businesses must review AI-assisted content before publishing. Voice input for AI-assisted composition is processed ephemerally for transcription and drafting; Twofer does not store raw voice audio, though transcript, usage, and support metadata may be retained to operate the service.",
    "privacy.providersTitle": "Service providers",
    "privacy.providersBody": "Twofer uses service providers such as Supabase for backend services, Stripe for approved web/admin business billing, push notification providers, map/location services, AI providers, diagnostics tools, and email/support providers where configured.",
    "privacy.noSaleTitle": "No sale or tracking",
    "privacy.noSaleBody": "Twofer does not sell personal data. Twofer does not use personal data for cross-company tracking for this launch posture. Business billing is handled through reviewed web/admin flows where applicable, not mobile subscription purchase, mobile checkout, Apple Pay, or Google Pay in the app.",
    "privacy.deletionTitle": "Account deletion",
    "privacy.deletionBody": "You can start account deletion inside the app under Account or Settings. You can also review the <a href=\"/delete-account\">delete account page</a>.",
    "businessTerms.title": "Business Terms | Twofer",
    "businessTerms.heading": "Business Terms",
    "businessTerms.lede": "Business account access is reviewed before activation.",
    "businessTerms.responsibilityTitle": "Business responsibility",
    "businessTerms.responsibilityBody": "Businesses are responsible for accurate profiles, offer content, schedules, quantities, eligibility terms, customer service, staff access, and honoring valid published offers according to displayed terms.",
    "businessTerms.aiTitle": "AI-assisted copy",
    "businessTerms.aiBody": "AI-assisted offer copy is a drafting tool. Businesses must review all copy, images, terms, and localized text before publishing and must not publish misleading or unsafe offers.",
    "businessTerms.prohibitedTitle": "Prohibited offers",
    "businessTerms.prohibitedBody": "Launch offers may not promote alcohol, tobacco or nicotine, cannabis or drugs, weapons, adult sexual services or products, prescription medication, illegal products or services, counterfeit goods, discriminatory offers, or misleading bait-and-switch offers.",
    "businessTerms.billingTitle": "Billing and cancellation",
    "businessTerms.billingBody": "Approved business billing is handled through reviewed web/admin flows and Stripe where applicable. The mobile app does not provide public subscription purchase, checkout, pricing links, Apple Pay, or Google Pay for launch.",
    "businessTerms.removalTitle": "Removal and suspension",
    "businessTerms.removalBody": "Twofer may remove offers, limit publishing, or suspend business accounts to protect customers, enforce policy, prevent abuse, or comply with law.",
    "thanks.title": "Business request received | Twofer",
    "thanks.heading": "Thanks.",
    "thanks.body": "Your Twofer business access request was received. Business tools are reviewed before activation. Use the same email in the Twofer app so your submitted details can appear there for review.",
    "waitlist.title": "Business Waitlist | Twofer",
    "waitlist.meta": "Twofer business waitlist for local businesses outside the current DFW launch fit.",
    "waitlist.heading": "Business Waitlist",
    "waitlist.body": "Thanks for your interest in Twofer. If your business is outside the current DFW launch area or outside the launch categories, we will keep your request for a later onboarding wave.",
    "review.title": "Business Review Pending | Twofer",
    "review.meta": "Twofer business profile review is pending.",
    "review.heading": "Review Pending",
    "review.body": "Your business profile is being reviewed. You can finish setup and preview an offer now. Publishing will unlock after verification.",
    "share.title": "Twofer shared offer",
    "share.eyebrow": "Shared offer",
    "share.heading": "Open this offer in Twofer.",
    "share.lede": "Shared offer links open in the Twofer app when it is installed. No private claim code or redemption token is shown on this web preview page.",
    "billing.common.webOnly": "Web-only billing",
    "billing.common.backBusiness": "Back to business access",
    "billing.start.title": "Business Billing | Twofer",
    "billing.start.heading": "Manage your Twofer business subscription securely with Stripe.",
    "billing.start.lede": "Checkout and card details stay outside the mobile app. After Stripe confirms a subscription, Twofer updates business access from Supabase.",
    "billing.start.trialTitle": "Access review first",
    "billing.start.trialBody": "Businesses can be reviewed before paid conversion. Payment is not required to submit a business access request.",
    "billing.start.stripeTitle": "Stripe handles payment",
    "billing.start.stripeBody": "Twofer stores only safe billing status and Stripe IDs. Raw card numbers and CVCs are never stored by Twofer.",
    "billing.status.title": "Billing Status | Twofer",
    "billing.status.heading": "Billing status is confirmed server-side.",
    "billing.status.lede": "Stripe webhooks update Twofer business access after checkout, portal changes, payment failures, cancellations, or refunds. If a recent payment is still pending, the app may take a moment to reflect the server status.",
    "billing.manage.title": "Manage Billing | Twofer",
    "billing.manage.eyebrow": "Stripe customer portal",
    "billing.manage.heading": "Manage billing securely",
    "billing.manage.lede": "Portal links are generated by authorized web/admin server functions and expire through Stripe. The mobile app never opens billing links.",
    "billing.manage.request": "Request a portal link",
    "billing.manage.cta": "Manage billing",
    "billing.success.title": "Billing Confirmed | Twofer",
    "billing.success.eyebrow": "Stripe confirmation",
    "billing.success.heading": "Billing confirmed",
    "billing.success.lede": "Stripe is confirming your subscription. Twofer will update your business access after the verified webhook reaches Supabase.",
    "billing.cancel.title": "Billing Canceled | Twofer",
    "billing.cancel.heading": "Billing was canceled",
    "billing.cancel.lede": "No subscription changes were made. If you need help continuing business access, contact Twofer support.",
    "billing.cancel.return": "Return to billing",
    "billing.addPayment.title": "Add Payment Method | Twofer",
    "billing.addPayment.heading": "Payment-method setup is not open yet.",
    "billing.addPayment.lede": "Twofer will only collect saved payment methods through an approved Stripe-hosted web flow with explicit consent. This route is disabled by default and is never launched from the mobile app.",
    "billing.addPayment.overview": "Billing overview",
  });

  Object.assign(messages.es, {
    "trial.jump": "Iniciar solicitud",
    "common.backHome": "Volver a Twofer",
    "common.getSupport": "Obtener soporte",
    "common.businessAccess": "Acceso de negocio",
    "common.questions": "Preguntas? Escribe a <a href=\"mailto:support@twoferapp.com\">support@twoferapp.com</a>.",
    "support.title": "Soporte | Twofer",
    "support.heading": "Soporte",
    "support.lede": "Para ayuda con Twofer, escribe a <a href=\"mailto:support@twoferapp.com\">support@twoferapp.com</a>.",
    "support.deleteTitle": "Eliminacion de cuenta",
    "support.deleteBody": "Puedes iniciar la eliminacion de cuenta dentro de la app Twofer en Cuenta o Configuracion. Tambien puedes contactar soporte si necesitas ayuda, o usar la <a href=\"/delete-account\">pagina de eliminacion de cuenta</a>.",
    "support.businessTitle": "Soporte para negocios",
    "support.businessBody": "Los negocios pueden pedir acceso en la pagina de negocios. Las cuentas de negocio se revisan antes de activarse. Las preguntas de facturacion se manejan por soporte de Twofer y flujos web/admin aprobados.",
    "support.reportTitle": "Reportar una oferta",
    "support.reportBody": "En la app, abre la pantalla de detalle de la oferta y elige Reportar esta oferta. Tambien puedes escribir a soporte con el nombre del negocio, titulo de la oferta y lo que ocurrio.",
    "delete.title": "Eliminar cuenta | Twofer",
    "delete.meta": "Como solicitar la eliminacion de tu cuenta y datos de Twofer.",
    "delete.heading": "Eliminar cuenta",
    "delete.lede": "Puedes solicitar la eliminacion de tu cuenta Twofer desde la app o contactando soporte.",
    "delete.appTitle": "Eliminar desde la app",
    "delete.appBody": "Inicia sesion en Twofer, abre Cuenta o Configuracion y elige la opcion de eliminacion de cuenta. La app te guiara por la confirmacion antes de iniciar la eliminacion.",
    "delete.emailTitle": "Solicitar ayuda por email",
    "delete.emailBody": "Escribe a <a href=\"mailto:support@twoferapp.com\">support@twoferapp.com</a> desde el email de tu cuenta Twofer e incluye \"Delete my Twofer account\" en el asunto.",
    "delete.retainedTitle": "Que puede conservarse",
    "delete.retainedBody": "Algunos registros de seguridad, transacciones, prevencion de fraude, negocio, soporte o legales pueden conservarse cuando sea requerido o anonimizarse cuando corresponda. Twofer no vende datos personales.",
    "terms.title": "Terminos de servicio | Twofer",
    "terms.heading": "Terminos de servicio",
    "terms.lede": "Estos terminos de lanzamiento cubren el uso de Twofer por consumidores.",
    "terms.usingTitle": "Uso de Twofer",
    "terms.usingBody": "Twofer ayuda a clientes a descubrir, reclamar y redimir ofertas locales. Tu eres responsable de tu cuenta, dispositivo y actividad en la app.",
    "terms.availabilityTitle": "Disponibilidad de ofertas",
    "terms.availabilityBody": "Las ofertas pueden tener limites de tiempo, cantidad, ubicacion u otros terminos mostrados. La disponibilidad puede cambiar antes de reclamar una oferta.",
    "terms.redemptionTitle": "Redencion",
    "terms.redemptionBody": "Las reclamaciones y pantallas de redencion QR deben usarse honestamente y solo para ofertas elegibles. Abuso, fraude, compartir cuentas o intentos de evadir limites pueden resultar en suspension.",
    "terms.limitsTitle": "Limites",
    "terms.limitsBody": "Twofer puede cambiar, pausar o discontinuar funciones y puede remover contenido o restringir cuentas para proteger a clientes, negocios y el servicio.",
    "privacy.title": "Politica de privacidad | Twofer",
    "privacy.effective": "Vigente el 1 de julio de 2026",
    "privacy.heading": "Politica de privacidad",
    "privacy.lede": "Esta politica describe los datos usados por la app Twofer actual y el flujo de lanzamiento del sitio web.",
    "privacy.collectTitle": "Datos que recopilamos",
    "privacy.collect1": "Datos de cuenta como nombre, email, identificadores de inicio de sesion y rol.",
    "privacy.collect2": "Datos de perfil de consumidor como codigo postal, cumpleanos, favoritos, reclamaciones, redenciones y preferencias.",
    "privacy.collect3": "Datos de ubicacion cuando eliges descubrimiento cercano por GPS, mas preferencias de ZIP como respaldo.",
    "privacy.collect4": "Tokens de notificaciones push y ajustes de alertas cuando optas por usarlos.",
    "privacy.collect5": "Datos de negocio como nombre, direccion, contacto, email, telefono, contenido de ofertas, imagenes, metricas y detalles de acceso del personal donde aplique.",
    "privacy.collect6": "Datos de solicitud de acceso de negocio enviados en el sitio web.",
    "privacy.collect7": "Uso, diagnosticos, mensajes de soporte y analitica de app necesarios para operar y mejorar Twofer.",
    "privacy.useTitle": "Como usamos los datos",
    "privacy.useBody": "Usamos datos para acceso de cuenta, descubrimiento de ofertas cercanas, reclamaciones, redencion QR, herramientas para comercios, creacion de ofertas con IA, soporte, prevencion de abuso, analitica, notificaciones y cumplimiento legal.",
    "privacy.aiTitle": "Herramientas con IA",
    "privacy.aiBody": "Las herramientas de IA para negocios ayudan a redactar texto de ofertas y materiales creativos relacionados. Los negocios deben revisar contenido asistido por IA antes de publicarlo. La entrada de voz para composicion con IA se procesa de forma efimera para transcripcion y redaccion; Twofer no almacena audio de voz crudo, aunque puede conservar transcripcion, uso y metadatos de soporte para operar el servicio.",
    "privacy.providersTitle": "Proveedores de servicio",
    "privacy.providersBody": "Twofer usa proveedores como Supabase para backend, Stripe para facturacion web/admin aprobada de negocios, proveedores de push, mapas/ubicacion, IA, diagnosticos y email/soporte donde esten configurados.",
    "privacy.noSaleTitle": "Sin venta ni rastreo",
    "privacy.noSaleBody": "Twofer no vende datos personales. Twofer no usa datos personales para rastreo entre companias en esta postura de lanzamiento. La facturacion de negocios se maneja mediante flujos web/admin revisados donde aplique, no compra de suscripcion movil, checkout movil, Apple Pay ni Google Pay en la app.",
    "privacy.deletionTitle": "Eliminacion de cuenta",
    "privacy.deletionBody": "Puedes iniciar la eliminacion de cuenta dentro de la app en Cuenta o Configuracion. Tambien puedes revisar la <a href=\"/delete-account\">pagina de eliminacion de cuenta</a>.",
    "businessTerms.title": "Terminos para negocios | Twofer",
    "businessTerms.heading": "Terminos para negocios",
    "businessTerms.lede": "El acceso de cuenta de negocio se revisa antes de activarse.",
    "businessTerms.responsibilityTitle": "Responsabilidad del negocio",
    "businessTerms.responsibilityBody": "Los negocios son responsables de perfiles precisos, contenido de ofertas, horarios, cantidades, terminos de elegibilidad, servicio al cliente, acceso del personal y de honrar ofertas publicadas validas segun los terminos mostrados.",
    "businessTerms.aiTitle": "Texto asistido por IA",
    "businessTerms.aiBody": "El texto de oferta asistido por IA es una herramienta de borrador. Los negocios deben revisar todo texto, imagenes, terminos y texto localizado antes de publicar y no deben publicar ofertas enganosas o inseguras.",
    "businessTerms.prohibitedTitle": "Ofertas prohibidas",
    "businessTerms.prohibitedBody": "Las ofertas de lanzamiento no pueden promover alcohol, tabaco o nicotina, cannabis o drogas, armas, servicios o productos sexuales para adultos, medicamentos recetados, productos o servicios ilegales, productos falsificados, ofertas discriminatorias u ofertas enganosas de bait-and-switch.",
    "businessTerms.billingTitle": "Facturacion y cancelacion",
    "businessTerms.billingBody": "La facturacion aprobada de negocios se maneja por flujos web/admin revisados y Stripe donde aplique. La app movil no ofrece compra publica de suscripcion, checkout, enlaces de precios, Apple Pay ni Google Pay para el lanzamiento.",
    "businessTerms.removalTitle": "Eliminacion y suspension",
    "businessTerms.removalBody": "Twofer puede remover ofertas, limitar publicacion o suspender cuentas de negocio para proteger clientes, hacer cumplir politicas, prevenir abuso o cumplir la ley.",
    "thanks.title": "Solicitud de negocio recibida | Twofer",
    "thanks.heading": "Gracias.",
    "thanks.body": "Recibimos tu solicitud de acceso de negocio en Twofer. Las herramientas de negocio se revisan antes de activarse. Usa el mismo email en la app Twofer para que tus datos enviados aparezcan alli para revision.",
    "waitlist.title": "Lista de espera de negocios | Twofer",
    "waitlist.meta": "Lista de espera de Twofer para negocios locales fuera del ajuste actual de lanzamiento en DFW.",
    "waitlist.heading": "Lista de espera de negocios",
    "waitlist.body": "Gracias por tu interes en Twofer. Si tu negocio esta fuera del area actual de lanzamiento en DFW o fuera de las categorias de lanzamiento, guardaremos tu solicitud para una ola de onboarding posterior.",
    "review.title": "Revision de negocio pendiente | Twofer",
    "review.meta": "La revision del perfil de negocio de Twofer esta pendiente.",
    "review.heading": "Revision pendiente",
    "review.body": "Tu perfil de negocio esta en revision. Puedes terminar la configuracion y previsualizar una oferta ahora. La publicacion se desbloqueara despues de la verificacion.",
    "share.title": "Oferta compartida de Twofer",
    "share.eyebrow": "Oferta compartida",
    "share.heading": "Abre esta oferta en Twofer.",
    "share.lede": "Los enlaces de ofertas compartidas abren la app Twofer cuando esta instalada. No se muestra ningun codigo privado de reclamacion ni token de redencion en esta vista web.",
    "billing.common.webOnly": "Facturacion solo web",
    "billing.common.backBusiness": "Volver al acceso de negocio",
    "billing.start.title": "Facturacion de negocio | Twofer",
    "billing.start.heading": "Administra tu suscripcion de negocio de Twofer de forma segura con Stripe.",
    "billing.start.lede": "Checkout y datos de tarjeta permanecen fuera de la app movil. Despues de que Stripe confirme una suscripcion, Twofer actualiza el acceso de negocio desde Supabase.",
    "billing.start.trialTitle": "Primero revision de acceso",
    "billing.start.trialBody": "Los negocios pueden revisarse antes de conversion pagada. No se requiere pago para enviar una solicitud de acceso de negocio.",
    "billing.start.stripeTitle": "Stripe maneja el pago",
    "billing.start.stripeBody": "Twofer almacena solo estado seguro de facturacion e IDs de Stripe. Numeros de tarjeta y CVC nunca se almacenan en Twofer.",
    "billing.status.title": "Estado de facturacion | Twofer",
    "billing.status.heading": "El estado de facturacion se confirma del lado del servidor.",
    "billing.status.lede": "Los webhooks de Stripe actualizan el acceso de negocio de Twofer despues de checkout, cambios de portal, fallas de pago, cancelaciones o reembolsos. Si un pago reciente sigue pendiente, la app puede tardar un momento en reflejar el estado del servidor.",
    "billing.manage.title": "Administrar facturacion | Twofer",
    "billing.manage.eyebrow": "Portal de cliente Stripe",
    "billing.manage.heading": "Administra la facturacion de forma segura",
    "billing.manage.lede": "Los enlaces del portal se generan por funciones web/admin autorizadas del servidor y vencen por Stripe. La app movil nunca abre enlaces de facturacion.",
    "billing.manage.request": "Solicitar enlace del portal",
    "billing.manage.cta": "Administrar facturacion",
    "billing.success.title": "Facturacion confirmada | Twofer",
    "billing.success.eyebrow": "Confirmacion de Stripe",
    "billing.success.heading": "Facturacion confirmada",
    "billing.success.lede": "Stripe esta confirmando tu suscripcion. Twofer actualizara tu acceso de negocio despues de que el webhook verificado llegue a Supabase.",
    "billing.cancel.title": "Facturacion cancelada | Twofer",
    "billing.cancel.heading": "La facturacion fue cancelada",
    "billing.cancel.lede": "No se hicieron cambios de suscripcion. Si necesitas ayuda para continuar el acceso de negocio, contacta soporte de Twofer.",
    "billing.cancel.return": "Volver a facturacion",
    "billing.addPayment.title": "Agregar metodo de pago | Twofer",
    "billing.addPayment.heading": "La configuracion de metodo de pago aun no esta abierta.",
    "billing.addPayment.lede": "Twofer solo recopilara metodos de pago guardados mediante un flujo web aprobado alojado por Stripe con consentimiento explicito. Esta ruta esta deshabilitada por defecto y nunca se lanza desde la app movil.",
    "billing.addPayment.overview": "Resumen de facturacion",
  });

  Object.assign(messages.ko, {
    "trial.jump": "요청 시작",
    "common.backHome": "Twofer로 돌아가기",
    "common.getSupport": "지원 받기",
    "common.businessAccess": "비즈니스 액세스",
    "common.questions": "질문이 있나요? <a href=\"mailto:support@twoferapp.com\">support@twoferapp.com</a>으로 이메일을 보내주세요.",
    "support.title": "지원 | Twofer",
    "support.heading": "지원",
    "support.lede": "Twofer 도움이 필요하면 <a href=\"mailto:support@twoferapp.com\">support@twoferapp.com</a>으로 이메일을 보내주세요.",
    "support.deleteTitle": "계정 삭제",
    "support.deleteBody": "Twofer 앱의 계정 또는 설정에서 계정 삭제를 시작할 수 있습니다. 도움이 필요하면 지원팀에 문의하거나 <a href=\"/delete-account\">계정 삭제 페이지</a>를 사용할 수도 있습니다.",
    "support.businessTitle": "비즈니스 지원",
    "support.businessBody": "비즈니스는 비즈니스 페이지에서 액세스를 요청할 수 있습니다. 비즈니스 계정은 활성화 전에 검토됩니다. 청구 문의는 Twofer 지원팀과 승인된 웹/관리자 청구 흐름을 통해 처리됩니다.",
    "support.reportTitle": "오퍼 신고",
    "support.reportBody": "앱에서 오퍼 상세 화면을 열고 이 오퍼 신고를 선택하세요. 비즈니스 이름, 오퍼 제목, 발생한 일을 지원팀에 이메일로 보낼 수도 있습니다.",
    "delete.title": "계정 삭제 | Twofer",
    "delete.meta": "Twofer 계정과 데이터 삭제를 요청하는 방법.",
    "delete.heading": "계정 삭제",
    "delete.lede": "앱 안에서 또는 지원팀에 문의하여 Twofer 계정 삭제를 요청할 수 있습니다.",
    "delete.appTitle": "앱에서 삭제",
    "delete.appBody": "Twofer에 로그인하고 계정 또는 설정을 연 뒤 계정 삭제 옵션을 선택하세요. 삭제가 시작되기 전에 앱이 확인 절차를 안내합니다.",
    "delete.emailTitle": "이메일로 도움 요청",
    "delete.emailBody": "Twofer 계정 이메일 주소에서 <a href=\"mailto:support@twoferapp.com\">support@twoferapp.com</a>으로 이메일을 보내고 제목에 \"Delete my Twofer account\"를 포함하세요.",
    "delete.retainedTitle": "보관될 수 있는 정보",
    "delete.retainedBody": "보안, 거래, 사기 방지, 비즈니스, 지원 또는 법적 기록은 필요한 경우 보관되거나 적절히 익명화될 수 있습니다. Twofer는 개인정보를 판매하지 않습니다.",
    "terms.title": "서비스 약관 | Twofer",
    "terms.heading": "서비스 약관",
    "terms.lede": "이 출시 약관은 소비자의 Twofer 사용에 적용됩니다.",
    "terms.usingTitle": "Twofer 사용",
    "terms.usingBody": "Twofer는 고객이 지역 오퍼를 발견하고, 클레임하고, 리딤하도록 돕습니다. 계정, 기기, 앱 활동에 대한 책임은 사용자에게 있습니다.",
    "terms.availabilityTitle": "오퍼 이용 가능성",
    "terms.availabilityBody": "오퍼에는 시간, 수량, 위치 또는 표시된 조건의 제한이 있을 수 있습니다. 오퍼를 클레임하기 전에 이용 가능성이 변경될 수 있습니다.",
    "terms.redemptionTitle": "리딤",
    "terms.redemptionBody": "클레임과 QR 리딤 화면은 정직하게, 적격 오퍼에만 사용해야 합니다. 남용, 사기, 계정 공유 또는 제한 우회 시도는 정지로 이어질 수 있습니다.",
    "terms.limitsTitle": "제한",
    "terms.limitsBody": "Twofer는 고객, 비즈니스, 서비스를 보호하기 위해 기능을 변경, 일시 중지 또는 종료하고 콘텐츠를 제거하거나 계정을 제한할 수 있습니다.",
    "privacy.title": "개인정보 처리방침 | Twofer",
    "privacy.effective": "시행일: 2026년 7월 1일",
    "privacy.heading": "개인정보 처리방침",
    "privacy.lede": "이 방침은 현재 Twofer 앱과 웹사이트 출시 흐름에서 사용하는 데이터를 설명합니다.",
    "privacy.collectTitle": "수집하는 데이터",
    "privacy.collect1": "이름, 이메일 주소, 로그인 식별자, 역할 등 계정 정보.",
    "privacy.collect2": "우편번호, 생일, 즐겨찾기, 클레임, 리딤, 선호도 등 소비자 프로필 정보.",
    "privacy.collect3": "GPS 기반 근처 검색을 선택할 때의 위치 데이터와 ZIP 백업 선호도.",
    "privacy.collect4": "동의한 경우 푸시 알림 토큰과 알림 설정.",
    "privacy.collect5": "비즈니스 이름, 주소, 담당자, 이메일, 전화, 오퍼 콘텐츠, 오퍼 이미지, 지표, 적용 가능한 직원 액세스 정보.",
    "privacy.collect6": "웹사이트에서 제출한 비즈니스 액세스 요청 정보.",
    "privacy.collect7": "Twofer 운영과 개선에 필요한 사용, 진단, 지원 메시지, 앱 분석 정보.",
    "privacy.useTitle": "데이터 사용 방법",
    "privacy.useBody": "계정 액세스, 근처 오퍼 검색, 클레임, QR 리딤, 상점 도구, AI 지원 오퍼 생성, 지원, 남용 방지, 분석, 알림, 법적 준수를 위해 데이터를 사용합니다.",
    "privacy.aiTitle": "AI 지원 도구",
    "privacy.aiBody": "비즈니스 AI 도구는 오퍼 문구와 관련 크리에이티브 초안을 돕습니다. 비즈니스는 게시 전 AI 지원 콘텐츠를 검토해야 합니다. AI 지원 작성용 음성 입력은 전사와 초안 작성을 위해 일시적으로 처리되며, Twofer는 원본 음성 오디오를 저장하지 않습니다. 다만 서비스 운영을 위해 전사, 사용, 지원 메타데이터는 보관될 수 있습니다.",
    "privacy.providersTitle": "서비스 제공업체",
    "privacy.providersBody": "Twofer는 백엔드용 Supabase, 승인된 웹/관리자 비즈니스 청구용 Stripe, 푸시 알림, 지도/위치, AI, 진단, 이메일/지원 제공업체를 구성된 범위에서 사용합니다.",
    "privacy.noSaleTitle": "판매 및 추적 없음",
    "privacy.noSaleBody": "Twofer는 개인정보를 판매하지 않습니다. 이 출시 단계에서 Twofer는 회사 간 추적 목적으로 개인정보를 사용하지 않습니다. 비즈니스 청구는 적용 가능한 경우 검토된 웹/관리자 흐름으로 처리되며 앱 내 모바일 구독 구매, 모바일 checkout, Apple Pay, Google Pay가 아닙니다.",
    "privacy.deletionTitle": "계정 삭제",
    "privacy.deletionBody": "앱의 계정 또는 설정에서 계정 삭제를 시작할 수 있습니다. <a href=\"/delete-account\">계정 삭제 페이지</a>도 확인할 수 있습니다.",
    "businessTerms.title": "비즈니스 약관 | Twofer",
    "businessTerms.heading": "비즈니스 약관",
    "businessTerms.lede": "비즈니스 계정 액세스는 활성화 전에 검토됩니다.",
    "businessTerms.responsibilityTitle": "비즈니스 책임",
    "businessTerms.responsibilityBody": "비즈니스는 정확한 프로필, 오퍼 콘텐츠, 일정, 수량, 자격 조건, 고객 서비스, 직원 액세스, 표시된 조건에 따른 유효한 게시 오퍼 이행에 책임이 있습니다.",
    "businessTerms.aiTitle": "AI 지원 문구",
    "businessTerms.aiBody": "AI 지원 오퍼 문구는 초안 도구입니다. 비즈니스는 게시 전 모든 문구, 이미지, 조건, 현지화된 텍스트를 검토해야 하며 오해의 소지가 있거나 안전하지 않은 오퍼를 게시해서는 안 됩니다.",
    "businessTerms.prohibitedTitle": "금지된 오퍼",
    "businessTerms.prohibitedBody": "출시 오퍼는 주류, 담배 또는 니코틴, 대마 또는 약물, 무기, 성인 성적 서비스나 제품, 처방약, 불법 제품이나 서비스, 위조품, 차별적 오퍼, 오해를 유도하는 bait-and-switch 오퍼를 홍보할 수 없습니다.",
    "businessTerms.billingTitle": "청구 및 취소",
    "businessTerms.billingBody": "승인된 비즈니스 청구는 적용 가능한 경우 검토된 웹/관리자 흐름과 Stripe를 통해 처리됩니다. 모바일 앱은 출시 기간 동안 공개 구독 구매, checkout, 가격 링크, Apple Pay, Google Pay를 제공하지 않습니다.",
    "businessTerms.removalTitle": "제거 및 정지",
    "businessTerms.removalBody": "Twofer는 고객 보호, 정책 집행, 남용 방지 또는 법 준수를 위해 오퍼를 제거하거나 게시를 제한하거나 비즈니스 계정을 정지할 수 있습니다.",
    "thanks.title": "비즈니스 요청 접수 | Twofer",
    "thanks.heading": "감사합니다.",
    "thanks.body": "Twofer 비즈니스 액세스 요청이 접수되었습니다. 비즈니스 도구는 활성화 전에 검토됩니다. 제출한 정보가 검토용으로 표시되도록 Twofer 앱에서 같은 이메일을 사용하세요.",
    "waitlist.title": "비즈니스 대기자 명단 | Twofer",
    "waitlist.meta": "현재 DFW 출시 조건에 맞지 않는 지역 비즈니스를 위한 Twofer 대기자 명단.",
    "waitlist.heading": "비즈니스 대기자 명단",
    "waitlist.body": "Twofer에 관심을 가져주셔서 감사합니다. 비즈니스가 현재 DFW 출시 지역 밖이거나 출시 카테고리 밖인 경우, 이후 온보딩 단계에서 검토할 수 있도록 요청을 보관합니다.",
    "review.title": "비즈니스 검토 대기 | Twofer",
    "review.meta": "Twofer 비즈니스 프로필 검토가 대기 중입니다.",
    "review.heading": "검토 대기 중",
    "review.body": "비즈니스 프로필을 검토 중입니다. 지금 설정을 완료하고 오퍼를 미리 볼 수 있습니다. 게시 기능은 인증 후 열립니다.",
    "share.title": "Twofer 공유 오퍼",
    "share.eyebrow": "공유 오퍼",
    "share.heading": "Twofer에서 이 오퍼를 여세요.",
    "share.lede": "공유 오퍼 링크는 앱이 설치된 경우 Twofer 앱에서 열립니다. 이 웹 미리보기 페이지에는 비공개 클레임 코드나 리딤 토큰이 표시되지 않습니다.",
    "billing.common.webOnly": "웹 전용 청구",
    "billing.common.backBusiness": "비즈니스 액세스로 돌아가기",
    "billing.start.title": "비즈니스 청구 | Twofer",
    "billing.start.heading": "Stripe로 Twofer 비즈니스 구독을 안전하게 관리하세요.",
    "billing.start.lede": "Checkout과 카드 정보는 모바일 앱 밖에서 처리됩니다. Stripe가 구독을 확인하면 Twofer는 Supabase에서 비즈니스 액세스를 업데이트합니다.",
    "billing.start.trialTitle": "액세스 검토 먼저",
    "billing.start.trialBody": "비즈니스는 유료 전환 전에 검토될 수 있습니다. 비즈니스 액세스 요청 제출에는 결제가 필요하지 않습니다.",
    "billing.start.stripeTitle": "Stripe가 결제를 처리합니다",
    "billing.start.stripeBody": "Twofer는 안전한 청구 상태와 Stripe ID만 저장합니다. 카드 번호와 CVC는 Twofer에 저장되지 않습니다.",
    "billing.status.title": "청구 상태 | Twofer",
    "billing.status.heading": "청구 상태는 서버에서 확인됩니다.",
    "billing.status.lede": "Stripe 웹훅은 checkout, 포털 변경, 결제 실패, 취소 또는 환불 후 Twofer 비즈니스 액세스를 업데이트합니다. 최근 결제가 아직 대기 중이면 앱에 서버 상태가 반영되기까지 잠시 걸릴 수 있습니다.",
    "billing.manage.title": "청구 관리 | Twofer",
    "billing.manage.eyebrow": "Stripe 고객 포털",
    "billing.manage.heading": "청구를 안전하게 관리",
    "billing.manage.lede": "포털 링크는 승인된 웹/관리자 서버 함수가 생성하며 Stripe를 통해 만료됩니다. 모바일 앱은 청구 링크를 열지 않습니다.",
    "billing.manage.request": "포털 링크 요청",
    "billing.manage.cta": "청구 관리",
    "billing.success.title": "청구 확인 | Twofer",
    "billing.success.eyebrow": "Stripe 확인",
    "billing.success.heading": "청구 확인됨",
    "billing.success.lede": "Stripe가 구독을 확인 중입니다. 검증된 웹훅이 Supabase에 도착한 뒤 Twofer가 비즈니스 액세스를 업데이트합니다.",
    "billing.cancel.title": "청구 취소 | Twofer",
    "billing.cancel.heading": "청구가 취소되었습니다",
    "billing.cancel.lede": "구독 변경은 이루어지지 않았습니다. 비즈니스 액세스 유지에 도움이 필요하면 Twofer 지원팀에 문의하세요.",
    "billing.cancel.return": "청구로 돌아가기",
    "billing.addPayment.title": "결제 수단 추가 | Twofer",
    "billing.addPayment.heading": "결제 수단 설정은 아직 열려 있지 않습니다.",
    "billing.addPayment.lede": "Twofer는 명시적 동의가 있는 승인된 Stripe 호스팅 웹 흐름을 통해서만 저장 결제 수단을 수집합니다. 이 경로는 기본적으로 비활성화되어 있으며 모바일 앱에서 실행되지 않습니다.",
    "billing.addPayment.overview": "청구 개요",
  });

  let activeLocale = "en";

  function normalizeLocale(value) {
    const raw = String(value || "").toLowerCase();
    if (raw.startsWith("es")) return "es";
    if (raw.startsWith("ko")) return "ko";
    return "en";
  }

  function preferredLocale() {
    try {
      const stored = window.localStorage.getItem(STORAGE_KEY);
      if (stored && SUPPORTED.includes(stored)) return stored;
    } catch {
      // Local storage can be disabled in private browsing.
    }
    const browserLocale = Array.isArray(navigator.languages) ? navigator.languages[0] : navigator.language;
    return normalizeLocale(browserLocale);
  }

  function textFor(key, locale = activeLocale) {
    return messages[locale]?.[key] || messages.en[key] || "";
  }

  function applyLocale(locale) {
    const nextLocale = SUPPORTED.includes(locale) ? locale : "en";
    activeLocale = nextLocale;
    document.documentElement.lang = nextLocale;

    document.querySelectorAll("[data-i18n]").forEach((node) => {
      const value = textFor(node.getAttribute("data-i18n") || "", nextLocale);
      if (value) node.textContent = value;
    });

    document.querySelectorAll("[data-i18n-html]").forEach((node) => {
      const value = textFor(node.getAttribute("data-i18n-html") || "", nextLocale);
      if (value) node.innerHTML = value;
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach((node) => {
      const value = textFor(node.getAttribute("data-i18n-placeholder") || "", nextLocale);
      if (value) node.setAttribute("placeholder", value);
    });

    document.querySelectorAll("[data-i18n-content]").forEach((node) => {
      const value = textFor(node.getAttribute("data-i18n-content") || "", nextLocale);
      if (value) node.setAttribute("content", value);
    });

    document.querySelectorAll("[data-i18n-aria-label]").forEach((node) => {
      const value = textFor(node.getAttribute("data-i18n-aria-label") || "", nextLocale);
      if (value) node.setAttribute("aria-label", value);
    });

    document.querySelectorAll("[data-language-option]").forEach((node) => {
      const isActive = node.getAttribute("data-language-option") === nextLocale;
      node.setAttribute("aria-pressed", String(isActive));
      node.classList.toggle("active", isActive);
    });

    try {
      window.localStorage.setItem(STORAGE_KEY, nextLocale);
    } catch {
      // Ignore storage failures; the visible translation still updates.
    }

    window.dispatchEvent(new CustomEvent("twofer:localechange", { detail: { locale: nextLocale } }));
  }

  function boot() {
    document.querySelectorAll("[data-language-option]").forEach((node) => {
      node.addEventListener("click", () => applyLocale(node.getAttribute("data-language-option") || "en"));
    });
    document.querySelectorAll("[data-site-menu-toggle]").forEach((node) => {
      node.addEventListener("click", () => {
        const nav = node.closest(".nav");
        const nextExpanded = node.getAttribute("aria-expanded") !== "true";
        node.setAttribute("aria-expanded", String(nextExpanded));
        if (nav) nav.classList.toggle("menu-open", nextExpanded);
      });
    });
    document.querySelectorAll(".nav-links a").forEach((node) => {
      node.addEventListener("click", () => {
        const nav = node.closest(".nav");
        const toggle = nav?.querySelector("[data-site-menu-toggle]");
        if (toggle) toggle.setAttribute("aria-expanded", "false");
        if (nav) nav.classList.remove("menu-open");
      });
    });
    applyLocale(preferredLocale());
  }

  window.TwoferI18n = {
    applyLocale,
    locale: () => activeLocale,
    t: (key) => textFor(key),
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot, { once: true });
  } else {
    boot();
  }
})();
